import { invoke } from "@tauri-apps/api/core";
import type {
  AppSettings,
  ComparisonItem,
  ExportResult,
  InsightsResponse,
  IndexStatus,
  MenuBarSnapshot,
  LiveActivityResponse,
  LiveSnapshot,
  NotchClearResult,
  NotchUiState,
  HookStatus,
  OverviewResponse,
  PhraseCloudResponse,
  ProjectControl,
  ProviderUsage,
  SessionDetail,
  SessionListQuery,
  SessionsResponse,
  SharePreview,
  ShareRenderRequest,
  SourceStatus,
  TaskSummary,
  VctiProfile,
} from "../types";

export const api = {
  overview: (range: string) => invoke<OverviewResponse>("get_overview", { range }),
  phraseCloud: (range: string) => invoke<PhraseCloudResponse>("get_phrase_cloud", { range }),
  liveSnapshot: () => invoke<LiveSnapshot>("get_live_snapshot"),
  liveActivity: () => invoke<LiveActivityResponse>("get_live_activity"),
  repairLiveHooks: () => invoke<HookStatus>("repair_live_hooks"),
  uninstallLiveHooks: () => invoke<HookStatus>("uninstall_live_hooks"),
  jumpToLiveSession: (id: string) => invoke<void>("jump_to_live_session", { id }),
  markNotchSessionsSeen: (ids: string[]) => invoke<void>("mark_notch_sessions_seen", { ids }),
  jumpToNotchCompletedSession: (id: string) =>
    invoke<void>("jump_to_notch_completed_session", { id }),
  deleteNotchCompletedSession: (id: string) =>
    invoke<void>("delete_notch_completed_session", { id }),
  clearNotchCompletedSessions: () =>
    invoke<NotchClearResult>("clear_notch_completed_sessions"),
  undoClearNotchCompletedSessions: (token: string) =>
    invoke<number>("undo_clear_notch_completed_sessions", { token }),
  setNotchExpanded: (expanded: boolean) => invoke<void>("set_notch_expanded", { expanded }),
  notchState: () => invoke<NotchUiState>("get_notch_state"),
  setNotchPinned: (pinned: boolean) => invoke<void>("set_notch_pinned", { pinned }),
  setNotchActivity: (hasActivity: boolean) => invoke<void>("set_notch_activity", { hasActivity }),
  setNotchLayout: (leftWingWidth: number, expandedHeight: number) =>
    invoke<void>("set_notch_layout", { leftWingWidth, expandedHeight }),
  tasks: (range: string) => invoke<TaskSummary[]>("get_tasks", { range }),
  mergeTasks: (taskIds: string[], title?: string) => invoke<string>("merge_tasks", { taskIds, title }),
  splitSession: (sessionId: string) => invoke<string>("split_session", { sessionId }),
  sessions: (query: SessionListQuery) =>
    invoke<SessionsResponse>("get_sessions", {
      range: query.range,
      agent: query.agent,
      search: query.search,
      model: query.model,
      project: query.project,
      verificationState: query.verificationState,
      attentionOnly: query.attentionOnly ?? false,
      codeOnly: query.codeOnly ?? false,
      commitOnly: query.commitOnly ?? false,
      page: query.page ?? 0,
      pageSize: query.pageSize ?? 50,
    }),
  sessionDetail: (id: string) => invoke<SessionDetail>("get_session_detail", { id }),
  comparison: (range: string) => invoke<ComparisonItem[]>("get_comparison", { range }),
  sources: () => invoke<SourceStatus[]>("get_sources"),
  setSourceSelected: (agent: string, selected: boolean) =>
    invoke<void>("set_source_selected", { agent, selected }),
  indexStatus: () => invoke<IndexStatus>("get_index_status"),
  refreshIndex: (force = false) => invoke<boolean>("refresh_index", { force }),
  menuSnapshot: (range: string) => invoke<MenuBarSnapshot>("get_menu_bar_snapshot", { range }),
  providers: () => invoke<ProviderUsage[]>("get_provider_usage"),
  refreshProviders: (credentialsAllowed: boolean, cursorDashboardUsageEnabled = false) =>
    invoke<ProviderUsage[]>("refresh_provider_data", { credentialsAllowed, cursorDashboardUsageEnabled }),
  settings: () => invoke<AppSettings>("get_app_settings"),
  setSetting: (key: keyof AppSettings, value: string) => invoke<void>("set_app_setting", { key, value }),
  previewShare: (request: ShareRenderRequest) => invoke<SharePreview>("render_share_preview", { request }),
  exportShare: (render: ShareRenderRequest, format: "png" | "svg", path: string) =>
    invoke<ExportResult>("export_share", { request: { ...render, format, path } }),
  renderSharePng: (request: ShareRenderRequest) => invoke<number[]>("render_share_png", { request }),
  exportTextFile: (path: string, content: string) => invoke<void>("export_text_file", { path, content }),
  insights: (range: string) => invoke<InsightsResponse>("get_insights", { range }),
  vctiProfile: (range: string) => invoke<VctiProfile>("get_vcti_profile", { range }),
  projects: () => invoke<ProjectControl[]>("get_projects"),
  excludeProject: (projectHash: string) => invoke<void>("exclude_project", { projectHash }),
  includeProject: (projectHash: string) => invoke<void>("include_project", { projectHash }),
  clearLocalData: () => invoke<void>("clear_local_data"),
  showMain: () => invoke<void>("show_main_window"),
  showSettings: () => invoke<void>("show_settings_window"),
  hideMenu: () => invoke<void>("hide_menu_bar_window"),
  openProviderStatus: (provider: string) => invoke<void>("open_provider_status", { provider }),
  quit: () => invoke<void>("quit_app"),
};
