import { invoke } from "@tauri-apps/api/core";
import type {
  AppSettings,
  ComparisonItem,
  DeepReviewPreview,
  DeepReviewRequest,
  ExportResult,
  InsightsResponse,
  IndexStatus,
  MenuBarSnapshot,
  LiveSnapshot,
  HookStatus,
  OverviewResponse,
  PhraseCloudResponse,
  PlaybookItem,
  ProjectControl,
  ProviderUsage,
  ReviewContent,
  ReviewDocument,
  ReviewsResponse,
  SavePlaybookRequest,
  SessionDetail,
  SessionsResponse,
  SharePreview,
  ShareRenderRequest,
  SourceStatus,
  TaskSummary,
  TodayResponse,
  VctiProfile,
} from "../types";

export const api = {
  overview: (range: string) => invoke<OverviewResponse>("get_overview", { range }),
  phraseCloud: (range: string) => invoke<PhraseCloudResponse>("get_phrase_cloud", { range }),
  liveSnapshot: () => invoke<LiveSnapshot>("get_live_snapshot"),
  repairLiveHooks: () => invoke<HookStatus>("repair_live_hooks"),
  uninstallLiveHooks: () => invoke<HookStatus>("uninstall_live_hooks"),
  jumpToLiveSession: (id: string) => invoke<void>("jump_to_live_session", { id }),
  setNotchExpanded: (expanded: boolean) => invoke<void>("set_notch_expanded", { expanded }),
  today: () => invoke<TodayResponse>("get_today"),
  tasks: (range: string) => invoke<TaskSummary[]>("get_tasks", { range }),
  mergeTasks: (taskIds: string[], title?: string) => invoke<string>("merge_tasks", { taskIds, title }),
  splitSession: (sessionId: string) => invoke<string>("split_session", { sessionId }),
  sessions: (range: string, agent: string | undefined, search: string | undefined, page = 0, pageSize = 50) =>
    invoke<SessionsResponse>("get_sessions", { range, agent, search, page, pageSize }),
  sessionDetail: (id: string) => invoke<SessionDetail>("get_session_detail", { id }),
  comparison: (range: string) => invoke<ComparisonItem[]>("get_comparison", { range }),
  sources: () => invoke<SourceStatus[]>("get_sources"),
  indexStatus: () => invoke<IndexStatus>("get_index_status"),
  refreshIndex: (force = false) => invoke<boolean>("refresh_index", { force }),
  menuSnapshot: () => invoke<MenuBarSnapshot>("get_menu_bar_snapshot"),
  providers: () => invoke<ProviderUsage[]>("get_provider_usage"),
  refreshProviders: (credentialsAllowed: boolean, cursorDashboardUsageEnabled = false) =>
    invoke<ProviderUsage[]>("refresh_provider_data", { credentialsAllowed, cursorDashboardUsageEnabled }),
  settings: () => invoke<AppSettings>("get_app_settings"),
  setSetting: (key: keyof AppSettings, value: string) => invoke<void>("set_app_setting", { key, value }),
  previewShare: (request: ShareRenderRequest) => invoke<SharePreview>("render_share_preview", { request }),
  exportShare: (render: ShareRenderRequest, format: "png" | "svg", path: string) =>
    invoke<ExportResult>("export_share", { request: { ...render, format, path } }),
  renderSharePng: (request: ShareRenderRequest) => invoke<number[]>("render_share_png", { request }),
  exportTextFile: (path: string, content: string) => invoke<void>("export_text_file", { path, content }),
  reviews: (reviewType?: string, targetId?: string) =>
    invoke<ReviewsResponse>("get_reviews", { reviewType, targetId }),
  generateReview: (reviewType: "task" | "session" | "daily" | "weekly", targetId: string, locale: string) =>
    invoke<ReviewDocument>("generate_review", { request: { reviewType, targetId, locale } }),
  previewDeepReview: (taskId: string, locale: string, mode: "cli" | "api", provider: string, model?: string) =>
    invoke<DeepReviewPreview>("preview_deep_review", { taskId, locale, mode, provider, model: model || undefined }),
  generateDeepReview: (request: DeepReviewRequest) =>
    invoke<ReviewDocument>("generate_deep_review", { request }),
  acceptReview: (id: string) => invoke<void>("accept_review", { id }),
  updateReview: (id: string, title: string, content: ReviewContent) =>
    invoke<void>("update_review", { request: { id, title, content } }),
  deleteReview: (id: string) => invoke<void>("delete_review", { id }),
  insights: (range: string) => invoke<InsightsResponse>("get_insights", { range }),
  vctiProfile: () => invoke<VctiProfile>("get_vcti_profile"),
  playbook: (search?: string) => invoke<PlaybookItem[]>("get_playbook", { search }),
  savePlaybook: (request: SavePlaybookRequest) => invoke<PlaybookItem>("save_playbook_item", { request }),
  deletePlaybook: (id: string) => invoke<void>("delete_playbook_item", { id }),
  projects: () => invoke<ProjectControl[]>("get_projects"),
  excludeProject: (projectHash: string) => invoke<void>("exclude_project", { projectHash }),
  includeProject: (projectHash: string) => invoke<void>("include_project", { projectHash }),
  clearLocalData: () => invoke<void>("clear_local_data"),
  showMain: () => invoke<void>("show_main_window"),
  showSettings: () => invoke<void>("show_settings_window"),
  hideMenu: () => invoke<void>("hide_menu_bar_window"),
  openProviderStatus: (provider: string) => invoke<void>("open_provider_status", { provider }),
  quit: () => invoke<void>("quit_app"),
};
